"""
Django settings for demoSimpleUI project.

Generated by 'django-admin startproject' using Django 3.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os
import time
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '43^@7k0s=7ub8pur-1&b^jgg!m(hyh57ht=9vt*@u_q(q(030^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'simpleui',
    'import_export',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'employe',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'demoSimpleUI.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'demoSimpleUI.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

# LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]


# 指定simpleui默认的主题,指定一个文件名，相对路径就从simpleui的theme目录读取
# SIMPLEUI_DEFAULT_THEME = 'e-green.css'

# 改变图标
# SIMPLEUI_DEFAULT_ICON = False
# SIMPLEUI_ICON = {
#     '组': 'fab fa-apple',
#     '用户': 'fas fa-user-tie'
# }

# 菜单
SIMPLEUI_CONFIG = {
    'system_keep': True,
    # 开启排序和过滤功能, 不填此字段为默认排序和全部显示, 空列表[] 为全部不显示.
    # 'menu_display': ['Simpleui', '测试', '动态菜单测试'],
    # ['Simpleui', '测试', '权限认证', '动态菜单测试'],
    'dynamic': True,    # 设置是否开启动态菜单, 默认为False. 如果开启, 则会在每次用户登陆时动态展示菜单内容
    'menus': [
                {
                    'name': 'Simpleui',
                    'icon': 'fas fa-code',
                    'url': 'https://gitee.com/tompeppa/simpleui'
                },
                # {
                #     'app': 'auth',
                #     'name': '权限和认证',
                #     'icon': 'fas fa-user-shield',
                #     'models': [{
                #             'name': '用户',
                #             'icon': 'fa fa-user',
                #             'url': 'auth/user/'
                #         },
                #         {
                #             'name': '组',
                #             'icon': 'fab fa-apple',
                #             'url': 'auth/group/'
                #         }
                #     ]
                # },
                {
                    # 自2021.02.01+ 支持多级菜单，models 为子菜单名
                    'name': '多级菜单',
                    'icon': 'fa fa-file',
                    # 二级菜单
                    'models': [{
                        'name': '百度',
                        'icon': 'far fa-surprise',
                        # 第三级菜单 ，
                        'models': [{
                              'name': '爱奇艺',
                              'url': 'https://www.iqiyi.com/dianshiju/'
                              # 第四级就不支持了，element只支持了3级
                            },
                            {
                                'name': '百度问答',
                                'icon': 'far fa-surprise',
                                'url': 'https://zhidao.baidu.com/'
                            }]
                        },
                        {
                            'name': '内网穿透',
                            'url': 'https://www.wezoz.com',
                            'icon': 'fab fa-github'
                        }
                    ]
                },
                {
                    'name': '动态菜单',
                    'icon': 'fa fa-desktop',
                    'models': [{
                            'name': 'home',
                            'url': 'http://baidu.com',
                            'icon': 'far fa-surprise'
                        }
                    ]
                }
            ]
        }


# SIMPLEUI_LOGIN_PARTICLES = False
#
# SIMPLEUI_HOME_PAGE = 'https://www.baidu.com'
# SIMPLEUI_HOME_TITLE = '百度一下你就知道'
# SIMPLEUI_HOME_ICON = 'fa fa-user'

SIMPLEUI_INDEX = 'https://www.88cto.com'

# SIMPLEUI_LOGO = 'https://avatars2.githubusercontent.com/u/13655483?s=60&v=4' # logo修改
SIMPLEUI_HOME_INFO = False  # 显示
SIMPLEUI_HOME_QUICK = True  # 显示
SIMPLEUI_HOME_ACTION = True
# SIMPLEUI_ANALYSIS = True
# SIMPLEUI_STATIC_OFFLINE = True
# SIMPLEUI_LOADING = False
